services:
  - type: web
    name: saucedemo-streamlit-demo
    env: docker
    dockerfilePath: ./Dockerfile.demo
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
